# Generated by Django 5.2 on 2025-04-19 09:01

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=apps.common.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('customer_id', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('tag', models.CharField(choices=[('vip', 'VIP'), ('frequent', 'Frequent'), ('regular', 'Regular'), ('inactive', 'Inactive')], default='regular', help_text='Customer classification for segmentation', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyPoints',
            fields=[
                ('id', models.CharField(default=apps.common.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
        ),
    ]
