# Generated by Django 5.2 on 2025-04-18 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerloyaltypoints',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AddField(
            model_name='customerloyaltypoints',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.ManyToManyField(related_name='loyalty_points', through='customers.CustomerLoyaltyPoints', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='customerloyaltypoints',
            unique_together={('company', 'customer')},
        ),
    ]
