# Generated by Django 5.2 on 2025-04-25 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agent_agent_id'),
        ('customers', '0005_remove_customer_created_by_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(default='agent', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='agents.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='+23400000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
