# Generated by Django 5.2 on 2025-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_id_alter_customerloyaltypoints_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='1bf3371a-d50f-41a5-98e8-fe7fdda44379', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerloyaltypoints',
            name='id',
            field=models.CharField(default='1bf3371a-d50f-41a5-98e8-fe7fdda44379', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
