# Generated by Django 5.2 on 2025-04-18 09:22

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default='ad1fc95b-6c5f-46ab-8d5a-c9a306e4f0b1', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=9, unique=True)),
                ('logo', models.ImageField(null=True, upload_to='', validators=[apps.common.validators.validate_image_size])),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
