# Generated by Django 5.2 on 2025-04-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='88a43366-b283-4284-afe9-1cefdc532a3c', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
