# Generated by Django 5.2 on 2025-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='lga',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='lagos', max_length=100),
            preserve_default=False,
        ),
    ]
