# Generated by Django 5.2 on 2025-05-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='10 Bendel Close, Victoria Island', max_length=100),
            preserve_default=False,
        ),
    ]
