# Generated by Django 5.2 on 2025-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='16885b8c-807c-42da-87c6-be55830185f3', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
