# Generated by Django 5.2 on 2025-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_address_company_lga_remove_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.CharField(default='Ikeja', max_length=100),
            preserve_default=False,
        ),
    ]
