# Generated by Django 5.2 on 2025-04-19 12:30

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[apps.common.validators.validate_image_size]),
        ),
    ]
