# Generated by Django 5.2 on 2025-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='eba4da0c-6c6b-4816-9f15-3a8cdc649222', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
