# Generated by Django 5.2 on 2025-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_push_notification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
