# Generated by Django 5.2 on 2025-04-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='fded4313-4bef-4c8a-8979-105b0919abea', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
