<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-16 20:51
=======
# Generated by Django 5.2 on 2025-04-17 06:30
>>>>>>> f8275b8258df32f240fb76131f7d66cd0390de3d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
<<<<<<< HEAD
            field=models.CharField(default='695deefd-a289-4107-9bb9-c4c7dfad5863', editable=False, max_length=36, primary_key=True, serialize=False),
=======
            field=models.CharField(default='1747e8a8-f8ca-4d5d-b150-1912e482f757', editable=False, max_length=36, primary_key=True, serialize=False),
>>>>>>> f8275b8258df32f240fb76131f7d66cd0390de3d
        ),
    ]
