# Generated by Django 5.2 on 2025-04-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp_user_otp_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id_back',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_front',
        ),
    ]
