# Generated by Django 5.2 on 2025-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='695deefd-a289-4107-9bb9-c4c7dfad5863', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
