# Generated by Django 5.2 on 2025-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='15c3b749-2e91-4ac1-9d0c-3bf681912d22', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
