# Generated by Django 5.2 on 2025-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='5d2cfbb5-e417-4954-9ded-f4d4710d5e7d', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
