# Generated by Django 5.2 on 2025-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default='ad1fc95b-6c5f-46ab-8d5a-c9a306e4f0b1', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20, null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
    ]
