# Generated by Django 5.2 on 2025-04-14 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('external_tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyloyaltypoints',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.ManyToManyField(null=True, related_name='loyalty_points', through='external_tables.CompanyLoyaltyPoints', to='companies.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyloyaltypoints',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external_tables.customer'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='external_tables.agent'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='external_tables.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='companyloyaltypoints',
            unique_together={('company', 'customer')},
        ),
    ]
