# Generated by Django 5.2 on 2025-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_tables', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('data', models.JSONField()),
                ('deliveredAt', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('readAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
