# Generated by Django 5.2 on 2025-04-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_tables', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default='8ba4e8ec-d448-4d05-8517-e0df734fb370', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyloyaltypoints',
            name='id',
            field=models.CharField(default='8ba4e8ec-d448-4d05-8517-e0df734fb370', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default='8ba4e8ec-d448-4d05-8517-e0df734fb370', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default='8ba4e8ec-d448-4d05-8517-e0df734fb370', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
