# Generated by Django 5.2 on 2025-04-24 20:33

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_tables', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.CharField(default=apps.common.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('resolution_notes', models.TextField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
