# Generated by Django 5.2 on 2025-04-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_tables', '0004_dispute_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dispute',
            table='disputes',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
