# Generated by Django 5.2 on 2025-04-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_tables', '0005_alter_dispute_table_alter_notification_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True},
        ),
    ]
