# Generated by Django 5.2 on 2025-04-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agent_agent_id'),
        ('customers', '0004_remove_customer_user_customer_created_by_and_more'),
        ('external_tables', '0006_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agent_id',
            field=models.ForeignKey(db_column='agent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_transactions', to='customers.customer'),
        ),
    ]
