# Generated by Django 5.2 on 2025-04-18 20:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default='eba4da0c-6c6b-4816-9f15-3a8cdc649222', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
