# Generated by Django 5.2 on 2025-04-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
        ('companies', '0004_company_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='companies.company'),
        ),
    ]
