# Generated by Django 5.2 on 2025-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='commission',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
