# Generated by Django 5.2 on 2025-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_commission_alter_agent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
