# Generated by Django 5.2 on 2025-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agent_id_alter_agent_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default='005d9cb3-ccd3-4c0b-ac51-9c9b9ec46666', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
