# Generated by Django 5.2 on 2025-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default='a2b47260-de66-4d39-abe4-8ebed19813b6', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
