# Generated by Django 5.2 on 2025-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.CharField(default='cdf31c5e-a9ad-4dd1-8e78-83f5a7388a22', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
